version: '3'
services:
  site1:
    image: nginx:1.26.2
    container_name: site1
    volumes:
      - ./site1/index.html:/usr/share/nginx/html/index.html
      - ./site1/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    networks:
      - nginx-network

  site2:
    image: nginx:1.26.2
    container_name: site2
    volumes:
      - ./site2/index.html:/usr/share/nginx/html/index.html
      - ./site2/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    networks:
      - nginx-network

  reverse_proxy:
    image: nginx:1.26.2
    container_name: proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./reverse-proxy/includes:/etc/nginx/includes
    ports:
      - "80:80"
    networks:
      - nginx-network

networks:
  nginx-network:
    name: nginx-network
    driver: bridge
