version: '3'
services:
  # Wordpress instance 1
  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp1_
    volumes:
      - ./wordpress1:/var/www/html
    networks:
      - proxy_network
    depends_on:
      - db

  # Wordpress instance 2
  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: w2_
    volumes:
      - ./wordpress2:/var/www/html
    networks:
      - proxy_network
    depends_on:
      - db

  # Wordpress instance 3
  wordpress3:
    image: wordpress:latest
    container_name: wordpress3
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp3_
    volumes:
      - ./wordpress3:/var/www/html
    networks:
      - proxy_network
    depends_on:
      - db

  # MySQL
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy_network

  # Proxy
  reverse_proxy:
    image: nginx:1.26.2
    container_name: proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/backend-not-found.html:/var/www/html/backend-not-found.html
      - ./reverse-proxy/includes:/etc/nginx/includes
    ports:
      - "80:80"
    networks:
      - proxy_network
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

networks:
  proxy_network:
    name: proxy_network
    driver: bridge

volumes:
  db_data:
